server:
  port: 8080
spring:
  application:
    name: backend-service
  datasource:
    url: ENC(nkJQUYug1EZDWnWow+ZEmkN07sJBd4d8NIBBcD+S5v8kDmHogwZxCGfbWAeClncrbLuQEJqeu6I=)
    username: ENC(e6DBEFY1ATNacRJnJ8Ce9Q==)
    password: ENC(mNJN6hGFLtvHjGAiUkjoow==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ENC(2Na13DVcC+KIm2zTPbStHdNqU/S0PMS0IDdKjderWsXYcoCwBMpf9w==)
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


server-uri: ENC(dJGHLEvJ0SpJney5vRsxYSGZI97+brfpKvDNSgkCfNw=)

jwt:
  access:
    secret: ENC(IFvNM2Z7dhbxX4VNwwgSA4E9k+hjaTFnQpyHHzolXKMiIdFRwnmMMPLHufWTar9ptGoHeDzhsdgizSKkXlkEtkNhamoOrr4yX3/+KVxgIUn56hfdpVgWPlkA3BwfuCSx)
    validity: ${JWT_ACCESS_VALIDITY:86400000}
  refresh:
    secret: ENC(IFvNM2Z7dhbxX4VNwwgSA4E9k+hjaTFnQpyHHzolXKMiIdFRwnmMMPLHufWTar9ptGoHeDzhsdgizSKkXlkEtkNhamoOrr4yX3/+KVxgIUn56hfdpVgWPlkA3BwfuCSx)
    validity: ${JWT_REFRESH_VALIDITY:604800000}
