server:
  port: 8080

spring:
  application:
    name: backend-service
  datasource:
    url: ENC(uk+kZN986V4o7tQWSpLhd7PnhZFGrQK5YN8+uoMHoX6fvvcgCK9I7Evm/OqNYbQZBJ/W8iM0Psm+WYMgaccZW4kI3mow1mMmLb3six1by6r9FkWa/GgZBz1spzkTbnAR8tVQnimxe4o=)
    username: ENC(ikYX5Ve5hvRD47opu21rYA==)
    password: ENC(ty3a5W2bwzaTvMkDwN0+447T5z60RSzE)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://129.154.54.225:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

cert-server-uri: ENC(Fa5dH8Atsi7Row6VPxZOKdWtXbdScLHa4ixdPPmUrbSzu00MDACHMASFY8xJDsz1)
server-uri: ENC(6lfUGZZVKl08qafTAVBbmxCKLzYIrzLoYrE1JAfccv1nZ/eeE9XztA==)

jwt:
  access:
    secret: ENC(IFvNM2Z7dhbxX4VNwwgSA4E9k+hjaTFnQpyHHzolXKMiIdFRwnmMMPLHufWTar9ptGoHeDzhsdgizSKkXlkEtkNhamoOrr4yX3/+KVxgIUn56hfdpVgWPlkA3BwfuCSx)
    validity: ${JWT_ACCESS_VALIDITY:86400000}
  refresh:
    secret: ENC(IFvNM2Z7dhbxX4VNwwgSA4E9k+hjaTFnQpyHHzolXKMiIdFRwnmMMPLHufWTar9ptGoHeDzhsdgizSKkXlkEtkNhamoOrr4yX3/+KVxgIUn56hfdpVgWPlkA3BwfuCSx)
    validity: ${JWT_REFRESH_VALIDITY:604800000}

# Actuator 및 Prometheus 메트릭 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      profile: prod
  prometheus:
    metrics:
      export:
        enabled: true

kafka:
  bootstrap-servers: ENC(lIYWFNGXMzTeW5I9mKazemx95Utdjq4O7uDYxIrADGI=)
  topics:
    jwt-verify-request: ENC(7SyF/txufkHbun6qFQl0cPlS8RVkKF5x)
    jwt-verify-reply: ENC(yXD1kihP7uOdFddMi3Cfb80s8Gzh4K6kFVVcVPw1PwE=)
    jwt-generate-request: ENC(8dUycB+Qm7pUIAD/NS6c23VbDb5CKM3ndKVACZZ0ztQ=)
    jwt-generate-reply: ENC(/CMfpXrYEv6ai1a8fAg59WgU/wqrmPXnhnRQkMFp0Qk=)
    mail-request-result: ENC(8ozKeDjUvFEZVQ9cU6JFNEtrcn/TVsEd7+yZZOfl6SQ=)
  timeout-ms: 5000
  consumer:
    group-id: ENC(WQRgxBvKTCYW+3T1hL68cPVfZ4QD81YAKpVz9gSNujHby2yJRpO7fQ==)
  producer:
    acks: all
    retries: 3
