name: unionmate prod CD 파이프라인

on:
  workflow_run:
    workflows: ["unionmate CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'dev' &&
      github.event.workflow_run.head_repository.full_name == github.repository

    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Docker 이미지 dev 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          key: ${{secrets.PROD_KEY}}
          script: |
            cd /home/ubuntu
            docker rm -f unionmate-prod || true
            docker compose pull unionmate-prod
            docker compose up -d --no-deps --force-recreate --pull always unionmate-prod
            docker image prune -f
