name: unionmate CI pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: jdk 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      - name: 테스트 실행 (스모크 포함)
        run: ./gradlew --no-daemon clean test -Dspring.profiles.active=test -Djasypt.encryptor.password=${{ secrets.JASYPT_PASSWORD }}


      - name: gradle 빌드
        if: success()
        run: ./gradlew clean build

      - name: 도커 로그인
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: 이미지 빌드 및 푸시
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/unionmate-be:latest
          push: true
